### ISSUE TITLE
Intuition behind the augmentation trick for flow?

### ISSUE THREAD

**Issue by YuMao1993** [yjxiong/anet2016-cuhk#10]
I am curious about what is the intuition behind the last line of [pyActionRec/utils/io.py](https://github.com/yjxiong/anet2016-cuhk/blob/master/pyActionRec/utils/io.py) ? It doesn't make sense to me. Is this just a trick you happened to find working well in practice?

```
crops[5:, range(0, stack_depth, 2), ...] = 255 - crops[5:, range(0, stack_depth, 2), ...]
```

**Comment by yjxiong** [comment]
This is not any trick but simple  math. When one flips the flow field horizontally, the x-direction of motion ought to be negated, which, in our representation, leads to the operation you mentioned.
