### ISSUE TITLE
ImportError: lib/dense_flow//build/libpydenseflow.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE

### ISSUE THREAD

**Issue by taraprasad73** [yjxiong/anet2016-cuhk#11]
I am receiving this error while trying to run the classify_video.py. I had to modify the build_all.sh file to make it work. Specifically libboost1.55-all-dev couldn't be installed, so I installed the 1.58 version using libboost-all-dev. Could this error be possibly linked to it, since the undefined symbol seems related to boost. **I am running the code on Ubuntu 16.04. Should I run this on Ubuntu 14.04 or some other version?**

On running - 
$ ANET_HOME="/home/user/Documents/anet2016-cuhk" python examples/classify_video.py --use_flow data/plastering.avi

Traceback (most recent call last):
  File "examples/classify_video.py", line 17, in <module>
    from pyActionRec.action_classifier import ActionClassifier
  File "/home/user/Documents/anet2016-cuhk/pyActionRec/action_classifier.py", line 3, in <module>
    from action_flow import FlowExtractor
  File "/home/user/Documents/anet2016-cuhk/pyActionRec/action_flow.py", line 7, in <module>
    from libpydenseflow import TVL1FlowExtractor
**ImportError: lib/dense_flow//build/libpydenseflow.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE**

The script file I used to bulid the code.
[modified_build_all.txt](https://github.com/yjxiong/anet2016-cuhk/files/925203/modified_build_all.txt)

**Comment by yjxiong** [comment]
This seems to be related to boost python. Try rebuilding the project after you installing the new boost version. Also please check whether there are multiple boost versions in your path.

**Comment by taraprasad73** [comment]
I had installed the latest boost before building the project. 

$ dpkg -s libboost-dev | grep 'Version'
Output - Version: 1.58.0.1ubuntu1

Also, I checked the .bashrc file and did not find boost in path. Could you mention which OS and specific environment was the original code tested on. I am using system python2.7. Should I use Anaconda?

**Comment by yjxiong** [comment]
We usually use ubuntu 14.04 or 16.04. For this kind of problems, using `ldd -r -v` to list the dependencies would be helpful.

**Comment by taraprasad73** [comment]
Thanks. Rebuilding helped. I was successful in running the project from scratch on Ubuntu 14.04.

**Comment by LuoweiZhou** [comment]
I got the same issue when running classify_video.py.
I built the project on Ubuntu 16.04 and installed boost-1.58 by default.
Any help? @yjxiong @taraprasad73

**Comment by LuoweiZhou** [comment]
Resolved. When compiling the dense flow module, do two things,
1. Modify line 23 of CMakeLists.txt to FIND_PACKAGE(PythonLibs 2.7 REQUIRED). The default one is for Python3.5m
2. Add option -DBOOST_ROOT with boost1.55 to when running CMake. You need to first install boost1.55 some place other than boost1.58
This works for the setting: Ubuntu 16.04, CUDA 8.0, Python 2.7, OpenCV 2.4.13, Boost 1.58

**Comment by yjxiong** [comment]
Thanks for posting your solution. The CMake modification makes sense. It seems that 16.04 by default has Python 3.5 installed. Meanwhile, boost 1.58 should be OK.

**Comment by LuoweiZhou** [comment]
Hi Yuanjun, yes, boost 1.58 alone should be fine. Initially, I add this to take #11 into account. Python2.7 is all we need. Thanks for sharing the code

**Comment by zohyan** [comment]
for my case I do not have an external graphics card, how do I proceed ??

**Comment by yjxiong** [comment]
@zohyan I would suggest getting a GPU.

**Comment by zohyan** [comment]
okay thanks! I will try
