### ISSUE TITLE
Problem while running classify.py in CPU mode

### ISSUE THREAD

**Issue by aneeshepari** [yjxiong/anet2016-cuhk#12]
I am getting the following error - `Cannot use GPU in CPU-only Caffe: check mode.`.  Can it be corrected by modifying classify_video.py? If possible can somebody suggest the modifications I need to make to run the example successfully without GPU.

**Comment by huajingyun** [comment]
try to modify anet2016-cuhk/pyActionRec/action_caffe.py 
```
17        # caffe.set_mode_gpu()
18        # caffe.set_device(device_id)
# ->
          caffe.set_mode_cpu()
```
