### ISSUE TITLE
How was your models trained?

### ISSUE THREAD

**Issue by joeyhng** [yjxiong/anet2016-cuhk#13]
Does your released model trained using the temporal annotations, or just the video level labels? 
Thanks.

**Comment by yjxiong** [comment]
The challenge models are trained with activity instances clipped according to the temporal annotations. 

If you are looking for approach using only video level label, please check out our CVPR17 paper

[UntrimmedNets for Weakly Supervised Action Recognition and Detection](https://arxiv.org/abs/1703.03329).

**Comment by joeyhng** [comment]
Thanks.
