### ISSUE TITLE
Error while running classify.py

### ISSUE THREAD

**Issue by kousik97** [yjxiong/anet2016-cuhk#14]
When I am trying to execute classify.py, I get the following error:

 File "examples/classify_video.py", line 13, in <module>
    anet_home = os.environ['ANET_HOME']
  File "/Users/Kousik/anaconda/envs/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'ANET_HOME'

**Comment by yjxiong** [comment]
`ANET_HOME` is an environmental variable. It should point to the root directory of this codebase.

**Comment by kousik97** [comment]
So, How do I fix this error?

**Comment by yjxiong** [comment]
Usually, we set an environmental variable in bash by 

`export ANET_HOME=<install location>`

Or one can specify this variable before a bash command, like

`ANET_HOME=<install location> python classifiy_video.py -h`

**Comment by Malithi-gif** [comment]
raceback (most recent call last):
  File "examples/classify_video.py", line 13, in <module>
    anet_home = os.environ['ANET_HOME']
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'ANET_HOME'

@yjxiong ,How to fix this in google colab?

**Comment by LucyQiu** [comment]
Hi all,
How to set ANET_CFG? I tried to set ANET_CFG as the same of ANET_HOME ( root directory of this codebase).
I still run into the error of:
File "/anet2016-cuhk/pyActionRec/__init__.py", line 1, in <module>
    from config import ANET_CFG
ImportError: cannot import name 'ANET_CFG' from 'config' (/anaconda/2019.10-p3.7/lib/python3.7/site-packages/config/__init__.py)

Please advise!

**Comment by LucyQiu** [comment]
@yjxiong thanks!

**Comment by LucyQiu** [comment]
I forgot mention, ANET_HOME issue fixed. @yjxiong @kousik97 @wanglimin @Malithi-gif

**Comment by Richard-Css** [comment]
> I forgot mention, ANET_HOME issue fixed. @yjxiong @kousik97 @wanglimin @Malithi-gif

How did you solve this problem?

**Comment by Richard-Css** [comment]
(anet) root@9bd8963cd7e6:~/anet2016-cuhk# python examples/classify_video.py data/plastering.avi
Traceback (most recent call last):
  File "examples/classify_video.py", line 17, in <module>
    from pyActionRec.action_classifier import ActionClassifier
  File "/root/anet2016-cuhk/pyActionRec/__init__.py", line 1, in <module>
    from config import ANET_CFG
ModuleNotFoundError: No module named 'config'

ANET_HOME=/root/anet2016-cuhk/
ANET_CFG=/root/anet2016-cuhk/

Hello, what is the problem? @LucyQiu @yjxiong
