### ISSUE TITLE
Is there have Inception-V3 rgb model trained on ActivityNet 1.3?

### ISSUE THREAD

**Issue by wlgcqh** [yjxiong/anet2016-cuhk#15]

**Comment by wlgcqh** [comment]
@yjxiong @wanglimin

**Comment by yjxiong** [comment]
What for?

**Comment by wlgcqh** [comment]
I want to verify the Inception-V3 rgb model,thank you!

**Comment by yjxiong** [comment]
There is a ResNet model released in this repo. You can use it for the RGB modality.

**Comment by bryanyzhu** [comment]
@yjxiong Hi, sorry to bother, I was just wondering, for Inception-V3, the input size requirement is 299x299. So may you explain more on how did you pre-process the video frames? Thanks a lot. 

Specifically, like your multi-scale cropping method. Before, you scale the image to 256x340, then scale ratio is set to [1, 0.875, 0.75, 0.66], which means the image size is [256, 224, 180, 158], then resize to 224x224. Now if the input size is 299x299, how do you do the multi-scale cropping in your experiments. Thanks a lot.

Another side question is, in data_transformer.cpp [here](https://github.com/yjxiong/caffe/blob/action_recog/src/caffe/data_transformer.cpp#L93), I don't quite get it why it is less than 3, and why 3? Thank you very much for your help. 
`abs(crop_h - net_input_height) < 3`
`crop_w - net_input_width) < 3`
