### ISSUE TITLE
no _caffe.so file

### ISSUE THREAD

**Issue by kousik97** [yjxiong/anet2016-cuhk#17]
I succesfully built caffe but I get the following error: 

Traceback (most recent call last):
  File "examples/classify_video.py", line 12, in <module>
    import caffe
  File "/home/user/koushik/anet2016-cuhk/lib/caffe-action/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/user/koushik/anet2016-cuhk/lib/caffe-action/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe

I am using the caffe given by this git repo.

**Comment by yjxiong** [comment]
Maybe you didn't compile the Python interface. It needs boost version >= 1.55 to make the CMake enable the Python interface. Please have a look at your libraries.

**Comment by kousik97** [comment]
How can I upgrade my boost version in ubuntu 14.04?

**Comment by yjxiong** [comment]
https://askubuntu.com/a/550568

Install `libboost1.55-all-dev`. Maybe first remove `libboost-all-dev` if it errors.

Or compile from source.

**Comment by kousik97** [comment]
I have succesfully installed boost1.55 :
 cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION" gives me:

BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
#define BOOST_LIB_VERSION "1_55"

While trying to build caffe, i get the following error:

[100%] Built target pycaffe
make: *** [all] Error 2
But I get the ._caffe.so file.

While trying to execute classify.py, I get the following error:


  File "lib/caffe-action//python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: /home2/koushik/anet2016-cuhk/lib/caffe-action/build/lib/libcaffe.so: undefined symbol: _ZN2cv6String10deallocateEv

**Comment by yjxiong** [comment]
After changing your boost version, remove all files under `build` and start again.

**Comment by Tikquuss** [comment]
I have this boost version : 1.65.1, but I have this mistake.
