### ISSUE TITLE
"caffe.LayerParameter" has no field named "bn_param"

### ISSUE THREAD

**Issue by wandering007** [yjxiong/anet2016-cuhk#2]
Run example `python examples/classify_video.py data/plastering.avi`  with error:  
```
libprotobuf ERROR google/protobuf/text_format.cc:172] Error parsing text-format caffe.NetParameter: 52:12: Message type "caffe.LayerParameter" has no field named "bn_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0901 16:20:27.977401 28675 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/resnet200_anet_2016_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by yjxiong** [comment]
Which Caffe version are you using? Please use the Caffe provided by us.

**Comment by wandering007** [comment]
@yjxiong I did follow the document and didn't update Caffe...Dose the shell code `git submodule update --remote` in `build_all.sh` update it?

**Comment by kousik97** [comment]
How did u fix this?

**Comment by wandering007** [comment]
@kousik97 Just use the specified-version caffe.

**Comment by MuLx10** [comment]
change bn_param to batch_norm_param

**Comment by yjxiong** [comment]
@MuLx10 

They are used by different layers. Please follow the original poster's solution.
