### ISSUE TITLE
ImportError: /root/caffe_video_end2end/3rd-party/opencv-2.4.13/build/lib/libopencv_gpu.so.2.4: undefined symbol: _ZN2cv3gpu9convertToERKNS0_6GpuMatERS1_ddP11CUstream_st

### ISSUE THREAD

**Issue by humengdoudou** [yjxiong/anet2016-cuhk#23]
I build the codebase successfully by running sh build_all.sh，but when running ANET_HOME="/root/caffe_video_end2end" python examples/classify_video.py data/plastering.avi
error happens as fellow：
Traceback (most recent call last):
  File "examples/classify_video.py", line 17, in <module>
    from pyActionRec.action_classifier import ActionClassifier
  File "/root/caffe_video_end2end/pyActionRec/action_classifier.py", line 3, in <module>
    from action_flow import FlowExtractor
  File "/root/caffe_video_end2end/pyActionRec/action_flow.py", line 7, in <module>
    from libpydenseflow import TVL1FlowExtractor
ImportError: /root/caffe_video_end2end/3rd-party/opencv-2.4.13/build/lib/libopencv_gpu.so.2.4: undefined symbol: _ZN2cv3gpu9convertToERKNS0_6GpuMatERS1_ddP11CUstream_st

above says the libopencv_gpu.so.2.4 is an undefined symbol，but in 3rd-party/opencv-2.4.13/build/lib by using ls -l，i can see that：
libopencv_gpu.so -> libopencv_gpu.so.2.4
libopencv_gpu.so.2.4 -> libopencv_gpu.so.2.4.13
libopencv_gpu.so.2.4.13

which means the libopencv_gpu.so.2.4 has already linked to libopencv_gpu.so.2.4.13. 

By the way，i have tested your caffe_tsn codebase，the linkage relation is the same like above，but i can run extract features、test、train correctly.

and i also compile the anet2016-cuhk code by using the caffe_tsn build_all.sh, the linkage relation also shows libopencv_gpu.so.2.4 has already linked to libopencv_gpu.so.2.4.13.   but it still shows the above bug.

**Comment by yjxiong** [comment]
If you have tsn code ready. You can copy the scripts and run them on top of TSN.

**Comment by humengdoudou** [comment]
i use docker to build your codebase. and after mapping anet2016-cuhk code to the TSN build based docker, it can run rightly, thanks for your reply.
