### ISSUE TITLE
About Temporal Activity Proposal

### ISSUE THREAD

**Issue by TimidLion** [yjxiong/anet2016-cuhk#25]
In ActivityNet Challenge for detection, you need to submit some segment that predicted as action,like this.
```
{
version: "VERSION 1.3",
results: {
  5n7NCViB5TU: [
      {
      label: "Discus throw",
      score: 0.64,
      segment: [24.25,38.08]
      },
      {
      label: "Shot put".
      score: 0.77,
      segment: [11.25, 19.37]
      }
  ]
}
external_data: {
  used: true, # Boolean flag. True indicates used of external data.
  details: "First fully-connected layer from VGG-16 pre-trained on ILSVRC-2012 training set", # String with details of your external data.
}
}
```
However, the demo with classify_video.py or with web demo I can only get the classification result.
How could I get such segment information?

**Comment by yjxiong** [comment]
This code is for ActivityNet 2016 Untrimmed Video classification track. There is no such requirement for submitting segment results.

If you need temporal action detection which produces segment predictions, please look at the code for our SSN paper

https://github.com/yjxiong/action-detection

**Comment by TimidLion** [comment]
@yjxiong Thanks, I'll move on.
