### ISSUE TITLE
Dockerfile request

### ISSUE THREAD

**Issue by lvaleriu** [yjxiong/anet2016-cuhk#28]
Hello! Firstly, I want to congratulate you for this project. 

I wanted to know if it is possible to give us a Dockerfile for building a docker image suited for your project since the current build script give us many errors.

Thanks!

**Comment by Soldelli** [comment]
Hi @lvaleriu, any luck building this in a Docker container? I know it has been a while but I hope you backed it up. 

Thanks.

**Comment by lvaleriu** [comment]
Hello. No, from memory I moved on a different project. New resources are available right now on github so I suggest you do some search.

**Comment by v-iashin** [comment]
If anyone will come across this issue and have the same request, you can check out https://github.com/yjxiong/anet2016-cuhk/issues/38
