### ISSUE TITLE
build dense_flow error

### ISSUE THREAD

**Issue by Zhuysheng** [yjxiong/anet2016-cuhk#29]
after run docker_server  build_all.sh, opencv is installed successfully, but when build dense_flow ,I meet the question, my cuda version is 9.0  
[ 50%] Building CXX object CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o
[ 64%] Building CXX object CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o
[ 64%] Building CXX object CMakeFiles/extract_cpu.dir/tools/extract_flow.cpp.o
[ 71%] Building CXX object CMakeFiles/pydenseflow.dir/src/py_denseflow.cpp.o
[ 78%] Linking CXX executable extract_gpu
[ 85%] Linking CXX executable extract_warp_gpu
[ 92%] Linking CXX executable extract_cpu
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: cannot find -lnppc
/usr/bin/ld: cannot find -lnppial
/usr/bin/ld: cannot find -lnppicc
/usr/bin/ld: cannot find -lnppicom
/usr/bin/ld: cannot find -lnppidei
/usr/bin/ld: cannot find -lnppif
/usr/bin/ld: cannot find -lnppig
/usr/bin/ld: cannot find -lnppim
/usr/bin/ld: cannot find -lnppist
/usr/bin/ld: cannot find -lnppisu
/usr/bin/ld: cannot find -lnppitc
/usr/bin/ld: cannot find -lnpps
/usr/bin/ld: cannot find -lcufft
collect2: error: ld returned 1 exit status
CMakeFiles/extract_cpu.dir/build.make:117: recipe for target 'extract_cpu' failed
make[2]: *** [extract_cpu] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/extract_cpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_cpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcudart
CMakeFiles/extract_gpu.dir/build.make:117: recipe for target 'extract_gpu' failed
/usrmake[2]: *** [extract_gpu] Error 1

**Comment by VSunN** [comment]
I have encountered the same problem. How did you solve it?
