### ISSUE TITLE
installing caffe from build_all.sh

### ISSUE THREAD

**Issue by AtousaTorabi** [yjxiong/anet2016-cuhk#3]
Hi,
I am trying to install caffe using your  build_all.sh. I have GPU with CUDA support the installed version of CUDA on my machine is 7.0. During caffe installation I get many cuda related errors such as :

/data05/A/ActivityNet/anet2016-cuhk/lib/caffe-action/include/caffe/neuron_layers.hpp(503): error: identifier "cudnnActivationDescriptor_t" is undefined

/data05/A/ActivityNet/anet2016-cuhk/lib/caffe-action/include/caffe/neuron_layers.hpp(587): error: identifier "cudnnActivationDescriptor_t" is undefined

/data05/A/ActivityNet/anet2016-cuhk/lib/caffe-action/include/caffe/neuron_layers.hpp(673): error: identifier "cudnnActivationDescriptor_t" is undefined

Is there any specific version of CUDA I need to install on machine? Could you please help me out to install caffe-action?

**Comment by yjxiong** [comment]
The target cuDNN version is v5.0 or v5.1. It looks like you have earlier version of cuDNN on your machine.

**Comment by AtousaTorabi** [comment]
This the version of CUDA I am using:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

Should I only use cuDNN version V5.0 to make it work? Please advice!

Thanks for your help

**Comment by AtousaTorabi** [comment]
Thanks I installed cuDNN version v5.0 and it worked.
