### ISSUE TITLE
error   python _caffe.so does not exist in caffe-action

### ISSUE THREAD

**Issue by AtousaTorabi** [yjxiong/anet2016-cuhk#4]
I have installed caffe-action using the "build-caffe" provided in build_all.sh. But it seems python caffe has not been compiled because '_caffe.so' does not exist at python branch and only its c++  file is there. Should I have to install pycaffe separately like with make pycaffe? Please advice!

I just did line below:
# build caffe

echo "Building Caffe"
cd ../../caffe-action
mkdir build 
cd build
OpenCV_DIR=../../../3rd-party/opencv-$version/build/ cmake ..
make -j32

Thanks for your help!

**Comment by yjxiong** [comment]
This usually means CMake cannot find the Python libraries for linking so it disables pycaffe. Please check the CMake output for Python related stuff.

BTW, please use 
`make -j32 install` instead of `make -j32`

**Comment by AtousaTorabi** [comment]
Thanks a lot for your help!  I managed to install and get _caffe.so. 
I have one last question. which CUDA version did you use? When Import caffe and read model prototype. I get this error:
I0922 12:43:54.095626 12928 net.cpp:160] Setting up caffe.SpatialConvolution_0
F0922 12:43:54.846365 12928 cudnn.hpp:95] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

I am using CUDA 7.0 and just installed cuDNN 5.0

**Comment by chuckcho** [comment]
i've been using cudnn4 and haven't done any test with cudnn 5. possibly that may be the source of issue.

**Comment by AtousaTorabi** [comment]
I have CUDA 7.0 with cuDNN 4.0 but in another thread yjxiong told me to use cuDNN 5.0 
@chuckcho  Have you been able to run the example with cudnn4?

**Comment by chuckcho** [comment]
@AtousaTorabi I'm totally messed up! Please disregard my previous message.

**Comment by AtousaTorabi** [comment]
I get the error:

I0922 12:43:54.095626 12928 net.cpp:160] Setting up caffe.SpatialConvolution_0
F0922 12:43:54.846365 12928 cudnn.hpp:95] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0) CUDNN_STATUS_BAD_PARAM 

at this line:
 self.__net_vec = [CaffeNet(x[0], x[1], dev_id,
                                   input_size=(340, 256) if x[4] else None
                                   ) for x in models]
This is my GPU info:
+------------------------------------------------------+
| NVIDIA-SMI 346.46     Driver Version: 346.46         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:04:00.0     Off |                    0 |
| N/A   38C    P0    62W / 149W |     55MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

I really do appreciate your help!

**Comment by AtousaTorabi** [comment]
I finally worked! I required to have CUDA 7.5 with cudnn 5.0 Thanks for your help!
