### ISSUE TITLE
Ok to realease resnet-200_solver.prototxt?

### ISSUE THREAD

**Issue by davidsonic** [yjxiong/anet2016-cuhk#5]
Much appreciation for making the framework publicly available. 
However, due to the resources and time required for training resnet, inappropriate parameter settings could be time-consuming and futile. I have been trying to reproduce the training process of resnet. As the ActivityNet Challenge is over, is it ok to release your training settings for resnet beforehand? Thanks

**Comment by yjxiong** [comment]
You can use the same solver parameters of [BN-inception](https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_solver.prototxt) in our released TSN framework. All models in ActivityNet challenge are trained with TSN.

Just change the `max_iter` and `stepsize` to `9000` and `4000`, respectively. TSN is quite stable against other parameters.

**Comment by xuzero** [comment]
Will you please release the resnet200 trained on the ImageNet? or can you tell me where did you get the resnet200 and the Inception V3? I can not find them by Google.Thanks!

**Comment by yjxiong** [comment]
@xuzero 

Resnet200 can be trained with the tools provided by Facebook folks [here](https://github.com/facebook/fb.resnet.torch). I think they also have pretrained model weights released.

Google has also released the inception V3 model in TensorFlow format [here](https://www.tensorflow.org/versions/r0.11/tutorials/image_recognition/index.html). 

There are a lot of tools on internet to convert torch or tensorflow pretrained models to Caffe format.

**Comment by xuzero** [comment]
I have find the tools of caffe2tensorflow and caffe2torch ,but i did not find a tool to convert the tensorflow model to caffe model, could you please tell me that tool if you know? Thanks for your help and nice work!
